### ISSUE TITLE
Focus shouldn't try to persist accross major mode changes

### ISSUE THREAD

**Issue by thblt** [larstvei/Focus#11]
See discussion on ffd97a5a3663103aa96945bb1d2f03481ab6229f.

**Comment by larstvei** [comment]
Agreed!

It was originally done because the focused area lingered when the major mode was changed, and there was no way to remove it (because the variables holding the overlays were killed). As you point out, minor modes generally shouldn't persist between major modes, and so a better solution is just to clean up on major mode change.

bfb6aaf should fix this.
