### ISSUE TITLE
Can't set thing to sentence in text mode

### ISSUE THREAD

**Issue by Hostuu** [larstvei/Focus#30]
Reproduce: emacs version 1:27.1+1-3ubuntu5.2, Linux Mint Cinnamon. M-x customize RET. Choose the following settings: Focus Mode to Thing: prog-mode defun, text-mode sentence, org-mode org-element. Edit a .txt file.

If done correctly, the focus should be on the paragraph, and not the sentence.

**Comment by Hostuu** [comment]
I had not set it to text-mode, but the bug persists

**Comment by larstvei** [comment]
I can't reproduce this. You want to change `text-mode` and derivative modes focus on sentences rather than paragraphs, right?

Than means that you have probably set `focus-mode-to-thing` to something like:

```emacs-lisp
(setq focus-mode-to-thing  '((prog-mode . defun)
                             (text-mode . sentence)
                             (org-mode . org-element)))
```

This works fine for me.

My guess is that you have set `sentence-end-double-space` to `t`, but only use a single space for ending your sentences.

See: https://www.gnu.org/software/emacs/manual/html_node/emacs/Sentences.html
And: https://www.gnu.org/software/emacs/manual/html_node/elisp/Filling.html#index-sentence_002dend_002ddouble_002dspace
